# Travis Variables:
# $TRAVIS_TEST_RESULT

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm



# Skip Installation Step
install: true



# Build LifeCycle
#apt addons:

#cache components:

#before_install:
  # Ubuntu Package or custom service

#install:

#before_script:
  #

script: phpunit tests/tests.php

#before_cache:

#after_success:
  # Additional step on build success e.g. as building documentation

#after_failure:
  # Additional step on build failed e.g. as sending log file

#before_deploy:

#deploy:

#after_deploy:

#after_script: