# Sources : https://docs.travis-ci.com/user/getting-started/

# ---------------- #
# --- Settings --- #
# ---------------- #

language: php

php:
    - 5.5

# ----------------------- #
# --- Build LifeCycle --- #
# ----------------------- #
